### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jpgochile** [Rickerd0613/PortScanDetector#2]
PortScanDetector   master  sudo python scanDetector.py  
Traceback (most recent call last):
  File "scanDetector.py", line 48, in <module>
    firewalld()
  File "scanDetector.py", line 20, in firewalld
    ["firewall-cmd", "--list-all-zones"]):
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Any idea?

**Comment by Rickerd0613** [comment]
Hi!

I'll look into this and get back to you soon. In the mean time, can you tell me what OS you're running, what firewall you are using (iptables or firewald), and what specific version of python you are running?

Thanks

**Comment by Rickerd0613** [comment]
It looks like the script is set to use firewalld without firewalld being installed. If you are using firewalld, make sure it is properly installed and you can run the following command: `firewall-cmd --list-all-zones`. If you are using iptables instead, make sure to set the variable isIpTables to True at the top of the file.

In the future, it would be great if this script could auto-detect which firewall the user is using. It shouldn't be too hard, I just don't have the time at the moment to work on it.
